package pageObjectModel;

import org.openqa.selenium.WebDriver;

public class AdminSideReport {
	WebDriver driver;

	public static void selectAccept() {
		if (Webelements.isDisplay(Locators.close)) {
			Webelements.click(Locators.close);
		}
	}
//login
	public void login(String username) {
		selectAccept();
		Webelements.wait(1000);
		Webelements.click(Locators.userName);
		Webelements.send(Locators.userName, username);
		Webelements.send(Locators.passWord, "Bu@Admin123");
		Webelements.click(Locators.signup);
	}
//logout
	public static void logout() {
		Webelements.click(Locators.dashboard);
		Webelements.click(Locators.userPic);
		Webelements.click(Locators.logout);
	}
//business overview
	public static void businessOverview() {
		Webelements.wait(1000);
		Webelements.click(Locators.reportPage);
		Webelements.wait(500);
		Webelements.click(Locators.bussinessSummary);
		Webelements.wait(5000);
		Webelements.click(Locators.reportPage);
		Webelements.click(Locators.salesIncome);
		Webelements.click(Locators.overallDropClick);
		Webelements.click(Locators.dropdownoversec);
		Webelements.click(Locators.actionDropClick);
		// Webelements.click(Locators.exportCsv);
		Webelements.click(Locators.dropFilter);
		Webelements.click(Locators.Selectcategorydropdown);
		Webelements.selectDropDownOption("category", "Admin Fund Deposit");
		Webelements.wait(500);
		Webelements.click(Locators.reportPage);
		Webelements.click(Locators.compensationExpenses);
		Webelements.click(Locators.overallDropClick);
		Webelements.click(Locators.dropdownoversec);
		Webelements.click(Locators.actionDropClick);
		// Webelements.click(Locators.exportCsv);
		Webelements.click(Locators.dropFilter);
		Webelements.click(Locators.Selectcategorydropdown);
		Webelements.selectDropDownOption("category", "Admin Fund Deposit");
		Webelements.wait(500);
		Webelements.click(Locators.reportPage);
		Webelements.click(Locators.transactionHistory);
		Webelements.click(Locators.overallDropClick);
		Webelements.click(Locators.dropdownoversec);
		Webelements.click(Locators.actionDropClick);
		// Webelements.click(Locators.exportCsv);
		Webelements.click(Locators.dropFilter);
		Webelements.click(Locators.Selectcategorydropdown);
		Webelements.selectDropDownOption("category", "Admin Fund Deposit");
		Webelements.wait(500);
		Webelements.click(Locators.reportPage);
		Webelements.click(Locators.memberTransactionHistory);
		Webelements.wait(500);
		Webelements.click(Locators.reportPage);
		Webelements.click(Locators.memberFinancialOverview);
		Webelements.click(Locators.overallDropClick);
		Webelements.click(Locators.commissionWallet);
		Webelements.wait(700);
		Webelements.click(Locators.overallDropClick);
		Webelements.click(Locators.purchaseWallet);
		Webelements.wait(700);
		Webelements.click(Locators.overallDropClick);
		Webelements.click(Locators.rewardWallet);
		Webelements.wait(700);
		Webelements.click(Locators.overallDropClick);
		Webelements.click(Locators.dividendWallet);
	}
//business report
	public static void businessReport() {
		Webelements.wait(1000);
		Webelements.click(Locators.reportPage);
		Webelements.click(Locators.upgradeHistory);
		Webelements.click(Locators.overallDropClick);
		Webelements.click(Locators.dropdownoversec);
		Webelements.wait(500);
		Webelements.click(Locators.actionDropClick);
		Webelements.click(Locators.userInput);
		Webelements.wait(500);
		Webelements.click(Locators.reportPage);
		Webelements.click(Locators.renewalHistory);
		Webelements.click(Locators.overallDropClick);
		Webelements.wait(500);
		Webelements.click(Locators.dropdownoversec);
		Webelements.wait(500);
		Webelements.click(Locators.actionDropClick);
		Webelements.click(Locators.userInput);
		Webelements.wait(500);
		Webelements.click(Locators.reportPage);
		Webelements.click(Locators.expiredUser);
		Webelements.click(Locators.overallDropClick);
		Webelements.click(Locators.dropdownoversec);
		Webelements.wait(500);
		Webelements.click(Locators.actionDropClick);
		Webelements.click(Locators.userInput);
		Webelements.wait(500);
		Webelements.click(Locators.reportPage);
		Webelements.click(Locators.rankVestedHistory);
		Webelements.click(Locators.overallDropClick);
		Webelements.wait(300);
		Webelements.click(Locators.userFullName);
		Webelements.wait(500);
		Webelements.click(Locators.reportPage);
		Webelements.click(Locators.rankLog);
		Webelements.click(Locators.rankLogDrop);
		Webelements.click(Locators.payRank);
		Webelements.wait(500);
		Webelements.click(Locators.rankLogDrop);
		Webelements.click(Locators.rankChoose);
		Webelements.wait(500);
		Webelements.click(Locators.reportPage);
		Webelements.click(Locators.carryHistory);
		Webelements.click(Locators.overallDropClick);
		Webelements.click(Locators.dropdownoversec);
		Webelements.wait(500);
		Webelements.click(Locators.actionDropClick);
		Webelements.click(Locators.uId);
		Webelements.wait(500);
		Webelements.click(Locators.reportPage);
		Webelements.click(Locators.rankRewardHistory);
		Webelements.click(Locators.overallDropClick);
		Webelements.wait(500);
		Webelements.click(Locators.userInput);
		Webelements.wait(500);
		Webelements.click(Locators.reportPage);
		Webelements.click(Locators.bonusConfigurationHistory);
		Webelements.click(Locators.allBonusDrop);
		Webelements.click(Locators.levelBonusAll);
		Webelements.wait(500);
		Webelements.click(Locators.reportPage);
		Webelements.click(Locators.rankModifiedHistory);
		Webelements.click(Locators.overallDropClick);
		Webelements.selectDropDownOption("rank-id", "Distributor");
	}
//business report
	public static void businessReportSecond() {
		Webelements.wait(1000);
		Webelements.click(Locators.reportPage);
		Webelements.click(Locators.bonusHistory);
		Webelements.wait(500);
		Webelements.click(Locators.overallDropClick);
		Webelements.wait(500);
		Webelements.click(Locators.exportCsv);
		Webelements.wait(1000);
		Webelements.click(Locators.closeOption);
		Webelements.wait(500);
		Webelements.click(Locators.actionDropClick);
		Webelements.selectDropDownOption("category", "Admin Fund Deposit");
		Webelements.wait(300);
		Webelements.click(Locators.userInput);
		Webelements.click(Locators.reportPage);
		Webelements.click(Locators.fundDepositHistory);
		Webelements.click(Locators.overallDropClick);
		Webelements.click(Locators.commissionWallet);
		Webelements.wait(700);
		Webelements.click(Locators.overallDropClick);
		Webelements.click(Locators.purchaseWallet);
		Webelements.wait(700);
		Webelements.click(Locators.overallDropClick);
		Webelements.click(Locators.rewardWallet);
		Webelements.wait(700);
		Webelements.click(Locators.overallDropClick);
		Webelements.click(Locators.dividendWallet);
		Webelements.wait(500);
		Webelements.click(Locators.actionDropClick);
		Webelements.click(Locators.dropdownOverall);
		Webelements.click(Locators.dropFilter);
		Webelements.click(Locators.userInput);
		Webelements.wait(500);
		Webelements.click(Locators.reportPage);
		Webelements.click(Locators.pendingEarnings);
		Webelements.click(Locators.overallDropClick);
		Webelements.click(Locators.commissionWallet);
		Webelements.wait(700);
		Webelements.click(Locators.overallDropClick);
		Webelements.click(Locators.purchaseWallet);
		Webelements.wait(700);
		Webelements.click(Locators.overallDropClick);
		Webelements.click(Locators.rewardWallet);
		Webelements.wait(700);
		Webelements.click(Locators.overallDropClick);
		Webelements.click(Locators.dividendWallet);
		Webelements.wait(500);
		Webelements.click(Locators.actionDropClick);
		Webelements.selectDropDownOption("category", "Admin Fund Deposit");
		Webelements.wait(300);
		Webelements.click(Locators.userInput);
		Webelements.click(Locators.reportPage);
		Webelements.wait(500);
		Webelements.click(Locators.holdingTankUsers);
		Webelements.click(Locators.overallDropClick);
		Webelements.click(Locators.uId);
		Webelements.wait(300);
		Webelements.click(Locators.reportPage);
		Webelements.wait(200);
		Webelements.click(Locators.peertoTransferHistory);
		Webelements.click(Locators.overallDropClick);
		Webelements.click(Locators.commissionWallet);
		Webelements.wait(700);
		Webelements.click(Locators.overallDropClick);
		Webelements.click(Locators.purchaseWallet);
		Webelements.wait(700);
		Webelements.click(Locators.overallDropClick);
		Webelements.click(Locators.rewardWallet);
		Webelements.wait(700);
		Webelements.click(Locators.overallDropClick);
		Webelements.click(Locators.dividendWallet);
		Webelements.wait(500);
		Webelements.click(Locators.reportPage);
		Webelements.wait(500);
		Webelements.click(Locators.failedCommissionLog);
		Webelements.wait(200);
		Webelements.click(Locators.failedAllLog);
		Webelements.click(Locators.failedRetailLog);
		Webelements.click(Locators.failedRewardLog);
		Webelements.click(Locators.failedPoolLog);
		Webelements.click(Locators.failedLevelLog);
		Webelements.click(Locators.failedBinaryLog);
		Webelements.click(Locators.failedBreakawayLog);
		Webelements.click(Locators.failedDemoLog);
		Webelements.click(Locators.failedRankLog);
		Webelements.click(Locators.failedSponsorLog);
		Webelements.click(Locators.failedRetailMatchLog);
		Webelements.click(Locators.failedrewardMatchLog);
		Webelements.click(Locators.failedPoolMatchLog);
		Webelements.click(Locators.failedLevelmatchLog);
		Webelements.click(Locators.failedBinaryMatchLog);
		Webelements.click(Locators.failedBreakawaymatchLog);
		Webelements.click(Locators.failedDemoMatchLog);
		Webelements.click(Locators.failedRankMatchAllLog);
		Webelements.click(Locators.failedSponsorMatchAllLog);
		Webelements.click(Locators.overallDropClick);
		Webelements.click(Locators.inputData);
		Webelements.wait(500);
		Webelements.click(Locators.reportPage);
		Webelements.click(Locators.subscriptionBackgroundJobs);
		Webelements.wait(300);
		Webelements.click(Locators.reportPage);
		Webelements.click(Locators.notificationHistory);
		Webelements.wait(200);
		Webelements.click(Locators.notifyExternalMail);
		Webelements.click(Locators.notifyInternalMail);
		Webelements.wait(300);
		Webelements.click(Locators.reportPage);
		Webelements.wait(200);
		Webelements.click(Locators.modifyEarningHistory);
		Webelements.click(Locators.overallDropClick);
		Webelements.click(Locators.commissionWallet);
		Webelements.wait(700);
		Webelements.click(Locators.overallDropClick);
		Webelements.click(Locators.purchaseWallet);
		Webelements.wait(700);
		Webelements.click(Locators.overallDropClick);
		Webelements.click(Locators.rewardWallet);
		Webelements.wait(700);
		Webelements.click(Locators.overallDropClick);
		Webelements.click(Locators.dividendWallet);
		Webelements.wait(500);
		Webelements.click(Locators.reportPage);
		Webelements.click(Locators.membersRoi);
		Webelements.click(Locators.overallDropClick);
		Webelements.click(Locators.userInput);
	}
//Team performance
	public static void teamPerformance() {
		Webelements.wait(1000);
		Webelements.click(Locators.reportPage);
		Webelements.click(Locators.rankOverview);
		Webelements.click(Locators.downlineMember);
		Webelements.click(Locators.downlineDrop);
		Webelements.wait(700);
		Webelements.click(Locators.downlineMember);
		Webelements.click(Locators.referDrop);
		Webelements.click(Locators.backArrow);
		Webelements.click(Locators.rankDropdown);
		Webelements.wait(700);
		Webelements.click(Locators.rankChoose);
		Webelements.wait(200);
		Webelements.click(Locators.rankDropdown);
		Webelements.wait(200);
		Webelements.click(Locators.payRank);
		Webelements.wait(500);
		Webelements.click(Locators.reportPage);
		Webelements.click(Locators.teamSalesOverview);
		Webelements.click(Locators.downlineMember);
		Webelements.click(Locators.downlineDrop);
		Webelements.wait(700);
		Webelements.click(Locators.downlineMember);
		Webelements.click(Locators.referDrop);
		Webelements.click(Locators.backArrow);
		Webelements.wait(500);
		Webelements.click(Locators.reportPage);
		Webelements.wait(700);
		Webelements.click(Locators.packageOverview);
		Webelements.click(Locators.downlineMember);
		Webelements.click(Locators.downlineDrop);
		Webelements.wait(700);
		Webelements.click(Locators.downlineMember);
		Webelements.click(Locators.referDrop);
		Webelements.click(Locators.backArrow);
		Webelements.wait(500);
		Webelements.click(Locators.reportPage);
		Webelements.click(Locators.earningsOverview);
		Webelements.click(Locators.downlineMember);
		Webelements.click(Locators.downlineDrop);
		Webelements.wait(700);
		Webelements.click(Locators.downlineMember);
		Webelements.click(Locators.referDrop);
		Webelements.click(Locators.backArrow);
		Webelements.wait(500);
		Webelements.click(Locators.reportPage);
		Webelements.click(Locators.joiningHistory);
		Webelements.click(Locators.downlineMember);
		Webelements.click(Locators.downlineDrop);
		Webelements.wait(700);
		Webelements.click(Locators.downlineMember);
		Webelements.click(Locators.referDrop);
		Webelements.click(Locators.backArrow);
		Webelements.wait(500);
		Webelements.click(Locators.reportPage);
		Webelements.click(Locators.salesHistory);
		Webelements.click(Locators.overallDropClick);
		Webelements.click(Locators.dropdownOverall);
		Webelements.wait(500);
		Webelements.click(Locators.downlineTeamSale);
		Webelements.click(Locators.downlineDropSale);
	}
	public static void ecommerceOrder() {
		Webelements.wait(1000);
    	Webelements.click(Locators.reportPage);
    	Webelements.click(Locators.allOrderstwo);
    	Webelements.click(Locators.overallDropClick);
	    Webelements.click(Locators.dropdownOverall);
	    Webelements.wait(500);
	   // Webelements.click(Locators.allOrders);
	   Webelements.click(Locators.reportPage);
	   Webelements.wait(700);
	   Webelements.click(Locators.ecommerceMycart);
	   Webelements.click(Locators.ecommerceUserPic);
	   Webelements.click(Locators.ecommerceDashboard);
	   Webelements.wait(700);
	   Webelements.click(Locators.reportPage);
	   Webelements.click(Locators.ordersbyStore);
	   Webelements.wait(500);
	   Webelements.click(Locators.reportPage);
	   Webelements.click(Locators.subscrption);
	   Webelements.wait(500);
	   Webelements.click(Locators.reportPage);
	   Webelements.click(Locators.productSalesStatistics);
	   Webelements.wait(200);
	   }
	public static void enrolmentOrders() {
    	//enrolment order
    	Webelements.wait(700);
    	Webelements.click(Locators.reportPage);
    	Webelements.click(Locators.membershipOrder);
    	Webelements.click(Locators.enrlAllOrders);
    	Webelements.click(Locators.pendingPaymentOrders);
    	Webelements.wait(500);
    	Webelements.click(Locators.enrlAllOrders);
    	Webelements.click(Locators.pendingFulfillmentOrders);
    	Webelements.wait(500);
    	Webelements.click(Locators.enrlAllOrders);
    	Webelements.click(Locators.fulfilledOrders);
    	Webelements.wait(500);
    	Webelements.click(Locators.enrlAllOrders);
    	Webelements.click(Locators.declinedOrders);
    	Webelements.wait(500);
    	Webelements.click(Locators.enrlAllOrders);
    	Webelements.click(Locators.Orders);
    	Webelements.wait(300);
    	Webelements.click(Locators.reportPage);
    	Webelements.wait(700);
    	Webelements.click(Locators.packageSubscription);
    	Webelements.wait(500);
//    	Webelements.click(Locators.reportPage);
//    	Webelements.click(Locators.fundDepositeOrders);
    	Webelements.click(Locators.dashboard);
    	System.out.println("Report page successfully verified");
    	
    }
		
	}

