package pageObjectModel;

public class Locators {

	public static String close = "//button[text()='Accept']";
	public static String bussinessSummary="//span[text()='Business Summary']";
	public static String userName = "//input[@name='username']";
	public static String passWord = "//input[@name='password']";
	public static String signup = "//input[@value='Sign In']";
	public static String dashboard = "//ul[@class='m-menu__nav m-menu__nav--dropdown-submenu-arrow']//li[1]//span[2]";
	public static String cardUpdate = "//div[@id='item-wrapper-popup-1']//button[text()='×']";
	public static String yesOption = "//button[text()='Yes']";
	public static String getName="//div[@class='m-portlet__username']";
	// User and admin logout
	public static String userPic = "//span[@class='m-topbar__userpic']//img";
	public static String logout = "//a[text()='Logout']";

	//My Account
	public static String reportPage="//span[text()='Reports']";
	public static String SalesOverviewOption="//span[text()='Sales Overview']";
	public static String overallDropClick="//li[@class='dropdown'][1]";
	public static String actionDropClick="//li[@class='dropdown'][2]";
	public static String filterDropClick="//li[@class='dropdown'][3]";
	public static String dropFilter="//a[text()=' Filter']";
	public static String dropdownOverall="//ul[@class='dropdown-menu package-dropdown show']//a[text()='Overall']";  //Overall, Today, Yesterday, This Week, Last Week, This Month, Last Month, This Year, Last Year
	public static String dropdownoversec="//ul[@class='m-subheader__links my-3 d-flex flex-wrap']//a[text()='Overall']";
	public static String dropdownAction= "//ul[@class='dropdown-menu package-dropdown show']//a[text()='All Tree']";
	public static String userInput="//input[@id='user']";
	public static String uId="//input[@id='uid']";
	public static String userFullName="//input[@id='user-full-name']";
	public static String fromDate="//input[@id='from-date']";
	public static String toDate="//input[@id='to-date']";
	public static String bonusHistory="//ul[@class='m-menu__inner']//span[text()='Bonus History']";
	public static String inputData="//input[@id='assoc-user']";
	public static String Selectcategorydropdown="//select[@id='category']";
	public static String PayoutHistory="//ul[@class='m-menu__inner']//span[text()='Payout History']";
    public static String commissionWallet="//a[text()='Commission Wallet']";
    public static String purchaseWallet="//a[text()='Purchase Wallet']";
    public static String rewardWallet="//a[text()='Rewards Wallet']";
    public static String dividendWallet="//a[text()='Dividend Wallet']";
    public static String activePayout="//a[text()='Active payout']";
    public static String allList="//a[text()=' All ']";
    public static String rejectedList="//a[text()='Rejected']";
    public static String completedList="//a[text()='Completed']";
    public static String cancelList="//a[text()='Cancelled']";
    public static String activepayoutList="//a[text()='Active Payout']";
    public static String searchButton="//input[@type='submit']";
    public static String packageUpgradeHistory="//ul[@class='m-menu__inner']//span[text()='Package Upgrade History']";
    public static String modifyEarningHistory="//ul[@class='m-menu__inner']//span[text()='Modify Earning History']";
    public static String rankRewardHistory="//ul[@class='m-menu__inner']//span[text()='Rank Reward History']";
    public static String failedCommissionLog="//span[text()='Failed Commission Log']";
    public static String failedAllLog="//a[text()='All Logs']";
    public static String failedRetailLog="//a[text()='Retail Profit Bonus']";
    public static String failedRewardLog="//a[text()='Reward Point Bonus']";
    public static String failedPoolLog="//a[text()='Pool Bonus']";
    public static String failedLevelLog="//a[text()='Level Bonus']";
    public static String failedBinaryLog="//a[text()='Binary Bonus']";
    public static String failedBreakawayLog="//a[text()='Breakaway']";
    public static String failedDemoLog="//a[text()='Demo']";
    public static String failedRankLog="//a[text()='Rank Achievement Bonus']";
    public static String failedSponsorLog="//a[text()='Sponsor Bonus']";
    public static String failedRetailMatchLog="//a[text()='Retail Profit Bonus Matching Bonus']";
    public static String failedrewardMatchLog="//a[text()='Reward Point Bonus Matching Bonus']";
    public static String failedPoolMatchLog="//a[text()='Pool Bonus Matching Bonus']";
    public static String failedLevelmatchLog="//a[text()='Level Bonus Matching Bonus']";
    public static String failedBinaryMatchLog="//a[text()='Binary Bonus Matching Bonus']";
    public static String failedBreakawaymatchLog="//a[text()='Breakaway Matching Bonus']";
    public static String failedDemoMatchLog="//a[text()='Demo Matching Bonus']";
    public static String failedRankMatchAllLog="//a[text()='Rank Achievement Bonus Matching Bonus']";
    public static String failedSponsorMatchAllLog="//a[text()='Sponsor Bonus Matching Bonus']";
    public static String renewalHistory ="//span[text()='Renewal History']";
    public static String rankHistory="//span[text()='Rank History']";
    public static String rankDropdown="//ul[@class='m-subheader__links my-3 d-flex flex-wrap']//a[text()=' Rank']";
    public static String rankLogDrop="//ul[@class='m-subheader__links my-3 d-flex flex-wrap']//a[contains(@class,'info dropdown-toggle m-btn--is-icon')]";
    public static String rankChoose="//ul[@class='dropdown-menu package-dropdown show']//a[text()='Rank']";
    public static String payRank="//ul[@class='dropdown-menu package-dropdown show']//a[text()='Pay rank']";
    public static String rankLog ="//span[text()='Rank Log']";
    public static String fundDepositHistory ="//span[text()='Fund Deposit History']";
    public static String p2pTransferHistory="//span[text()='P2P Transfer History']";
    public static String carryHistory="//span[text()='Carry History']";
    public static String rankOverview ="//span[text()='Rank Overview']";
    public static String downlineMember="//ul[@class='m-subheader__links my-3 d-flex flex-wrap']//a[text()=' Downline Members']";
    public static String downlineDrop="//ul[@class='dropdown-menu package-dropdown show']//a[text()='Downline Members']";
    public static String referDrop="//ul[@class='dropdown-menu package-dropdown show']//a[text()='Referred Members']";
    public static String backArrow="//span[text()='Back']";
    public static String teamSalesOverview="//span[text()='Team Sales Overview']";
    public static String packageOverview="//span[text()='Package Overview']";
    public static String earningsOverview="//span[text()='Earnings Overview']";
    public static String joiningHistory="//span[text()='Joining History']";
    public static String salesHistory="//span[text()='Sales History']";
    public static String downlineTeamSale="//a[text()=' Downline Team Sales']";
    public static String downlineDropSale="//ul[@class='dropdown-menu package-dropdown show']//a[text()='Downline Team Sales']";
    public static String downlineReferSale="//ul[@class='dropdown-menu package-dropdown show']//a[text()='Referral Team Sales']";
    public static String ecommerceMyOrder="//span[normalize-space()='My Orders']";
    public static String allOrders="//ul[@class='m-subheader__links my-3 d-flex flex-wrap']//a[@class='btn btn-sm btn-light--brand dropdown-toggle' and text()='All Orders']";
    public static String allOrderstwo="//span[text()='All Orders ']";
    public static String ecommerceMycart="//span[text()='My Cart ']";
    public static String ecommerceUserPic="//span[@class='nav-userpic']";
    public static String ecommerceDashboard="//span[text()='Dashboard']";
    public static String ecommerceSubscribe="//span[normalize-space()='My Subscriptions']";
    public static String subscrption="//span[text()='Subscriptions']";
    public static String membershipOrder="//span[text()='Membership Orders']";
    public static String packageSubscription="//span[text()='Package Subscriptions']";
    public static String fundDepositeOrders="//span[text()='Fund Deposit Orders']";
    public static String enrlAllOrders="//ul[@class='m-subheader__links my-3 d-flex flex-wrap']//a[@class='btn btn-sm btn-light--brand dropdown-toggle']";
    public static String pendingPaymentOrders="//ul[@class='dropdown-menu dropdown-menu-right show']//a[text()='Pending Payment Orders']";
    public static String pendingFulfillmentOrders="//ul[@class='dropdown-menu dropdown-menu-right show']//a[text()='Pending Fulfillment Orders']";
    public static String fulfilledOrders="//ul[@class='dropdown-menu dropdown-menu-right show']//a[text()='Fulfilled Orders']";
    public static String declinedOrders="//ul[@class='dropdown-menu dropdown-menu-right show']//a[text()='Declined Orders']";
    public static String Orders="//ul[@class='dropdown-menu dropdown-menu-right show']//a[text()='All Orders']";
   //Admin side
    public static String closeOption="//button[text()='Close']";
    public static String salesIncome="//span[text()='Sales & Income']";
    public static String exportCsv="//a[text()='Export CSV']";
    public static String compensationExpenses="//span[text()='Compensation & Expenses']";
    public static String transactionHistory="//span[text()='Transactions History']";
    public static String memberTransactionHistory="//span[text()='Members Transaction History']"; 
    public static String memberFinancialOverview="//span[text()='Members Financial Overview']";
    public static String upgradeHistory="//span[text()='Upgrade History']";
    public static String expiredUser="//span[text()='Expired Users']";
    public static String rankVestedHistory="//span[text()='Rank Vested History']";
    public static String bonusConfigurationHistory="//span[text()='Bonus Configuration History']";
    public static String allBonusDrop="//ul[@class='m-subheader__links my-3 d-flex flex-wrap']";
    public static String levelBonusAll="//a[text()='Level Bonus']";
    public static String rankModifiedHistory="//span[text()='Rank Modified History']";
    public static String pendingEarnings="//ul[@class='m-menu__inner']//span[text()='Pending Earnings']";
    public static String holdingTankUsers="//span[text()='Holding Tank Users']";
    public static String peertoTransferHistory="//span[text()='P2P Transfer History']";
    public static String subscriptionBackgroundJobs="//span[text()='Subscription Background Jobs']";
    public static String notificationHistory="//span[text()='Notification History']";
    public static String notifyExternalMail="//a[text()='External Mail']";
    public static String notifyInternalMail="//a[text()='Internal Mail']";
    public static String membersRoi="//span[text()='Members ROI']";
    public static String ordersbyStore="//span[text()='Orders by Stores']";
    public static String productSalesStatistics="//span[text()='Product Sales Statistics']";
}


